### ISSUE TITLE
Can't install the crate

### ISSUE THREAD

**Issue by ondrowan** [Swoorup/dgraph-rs#1]
Protobufs are compiled during build step, but [protoc-grpcio](https://github.com/mtp401/protoc-grpcio) requires `protoc` CLI utility to be installed to actually compile anything. Therefore if users of this library don't have this utility installed, this crate won't build. Wouldn't it be better idea to precompile protobufs and keep generated files in repo, like official (Go and JS) clients do?

**Comment by Swoorup** [comment]
Good point, I was on dilemma on this decision earlier. For me, was easier to have to generated automatically.
