### ISSUE TITLE
gRPC errors on client connect and query

### ISSUE THREAD

**Issue by maxburke** [Swoorup/dgraph-rs#13]
Hi!

I'm trying out this client and I'm getting  a couple errors. First, I get this error when I create a client:

```
E1203 14:06:23.973404816    6831 uri_parser.cc:46]           bad uri.scheme: ''
E1203 14:06:23.973503065    6831 uri_parser.cc:52]                            ^ here
E1203 14:06:23.973512562    6831 http_proxy.cc:58]           cannot parse value of 'http_proxy' env var
```

And this error when I make a query:

```
Err(
    GrpcError(
        RpcFailure(
            RpcStatus {
                status: Internal,
                details: Some(
                    "grpc: error unmarshalling request: proto: wrong wireType = 2 for field StartTs",
                ),
            },
        ),
    ),
)
```

The server I'm connecting to is at localhost:9080; has anyone seen this issue before?

**Comment by ondrowan** [comment]
What version of Dgraph are you using? If it's 1.1, it's not supported yet, but there's a PR #12 for it.

**Comment by maxburke** [comment]
Ahh, yeah, it was a version issue. I backed down to 1.0.17 and it seems fine now.

Why are there breaking connectivity issues between a minor version update of Dgraph? Shouldn't all 1.x versions be compatible, minus support for new features introduced in the newer versions?

**Comment by ondrowan** [comment]
I don't know why they chose to break compatibility in minor version. It's also just couple of small changes in their API, nothing serious, but it still means some rewriting needs to be done on our side. I'm also still unsure how to approach this. I'd probably prefer keeping compatibility with both versions, but some people suggested abandoning 1.0.X completely in newer versions of this library.

**Comment by maxburke** [comment]
Got it. Thanks, @ondrowan 

It would be nice to have compatibility between the two versions; it would mean that we could better manage the upgrade of our Dgraph servers and Rust clients without having to synchronize updates. For example, we could deploy a new client that supports both v1.0 and v1.1 so that when we upgrade our servers we have minimal client downtime.

**Comment by maxburke** [comment]
@ondrowan / @Swoorup Any updates on timelines for merging dgraph 1.1 support?

**Comment by ondrowan** [comment]
@maxburke Sorry for the delay, I was sick and then swamped with work. I'll do it most likely this weekend.
