### ISSUE TITLE
Geo types being handled strangely

### ISSUE THREAD

**Issue by davedbase** [Swoorup/dgraph-rs#17]
I'm having trouble with a `geo` predicate not being recorded correctly. I attempted two different implementations. The first was to pass a vec of float: `coordinates: vec![ lat, lon ]`.

Then noted that it required a vec u8 and attempted coercing the values `vec![ ( lat / 100000.0) as u8, ( lon / 100000.0) as u8 ]`.

The other was to use WKB:

```rust
let lat: f64 = location.lat.into();
let lon: f64 = location.lon.into();
if lat > 90.0 || lat < -90.0 || lon > 180.0 || lon < -180.0 {
    return Err(Status::invalid_argument("LAT_LNG_INVALID"));
}
let p: Geometry<f64> = Geometry::Point(Point::new(lat, lon));
let wkb = geom_to_wkb(&p);
```
I attempted WKB because the source seems to indicate that's what it's expecting https://github.com/Swoorup/dgraph-rs/blob/7611de46cc6456c7591341bd8f34fc043eb7c684/src/protos/dgraph11/api.rs#L3045

When I do that I get a panic. I'm using 1.1 btw:

```
thread 'main' panicked at 'failed to create data: GrpcError(RpcFailure(RpcStatus { status: Unknown, details: Some("Cannot convert int to type geo") }))', src/server.rs:1:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ondrowan** [comment]
I have commited 2 examples with geo mutations / queries:

* `examples/geo_geojson.rs` - This one uses `geojson` crate
* `examples/geo_simple.rs` - This one uses custom structure representing `Point`

You can run those with `cargo run --no-default-features --features dgraph-1-1 --example geo_geojson` and `cargo run --no-default-features --features dgraph-1-1 --example geo_simple`.

I'll document those example properly later.

Hope it helps!

**Comment by ondrowan** [comment]
Also, here are relevant parts of Dgraph docs describing how to use geo values:

* https://docs.dgraph.io/mutations/#geolocation-support
* https://docs.dgraph.io/query-language/#geolocation

**Comment by davedbase** [comment]
Thanks that really helped clarify things.
