### ISSUE TITLE
Update mutation not erroring or actually saving

### ISSUE THREAD

**Issue by davedbase** [Swoorup/dgraph-rs#18]
I'm having some trouble, most likely due to incorrect use (again). I'm neither receiving an error or seeing the effect take place. I have a struct that looks like so:

```rust
// Model for updating a user
#[derive(Serialize, Deserialize, Default, Debug)]
pub struct UserUpdate {
    pub uid: String,
    pub username: Option<String>,
    pub password: Option<String>,
    pub email: Option<String>,
    pub updated_at: Option<DateTime<Utc>>
}
```
I then have an endpoint that receives a request an updates the user conditional on if values exist in the payload:
```rust
let req = request.into_inner();
let mut user = UserUpdate {
    uid: usr.unwrap().uid.to_string(),
    username: None,
    password: None,
    email: None,
    updated_at: Some(Utc::now())
};
// Update values if supplied to the endpoint
if req.username.to_string() != "" {
    user.username = Some(req.username.to_string());
}
if req.email.to_string() != "" {
    user.email = Some(req.email.to_string());
}
if req.password.to_string() != "" {
    user.password = Some(req.password.to_string());
}
// Submit the record to upgrade
let mut txn = self.graph.new_txn();
let mut mututation = dgraph::Mutation::new();
mututation.set_set_json(serde_json::to_vec(&user).expect("Invalid JSON"));
// Finalize the commit
let res = txn.commit();
if res.is_err() {
    return Err(Status::internal("INTERNAL_ERROR"));
}
```
There might be a better way to structure this but it's the only way I could think of structuring it. When I run a request there's no error, the result comes back successful but my record isn't modified at all. I'm passing in the correct uid and everything.

Wondering where I went wrong :-/ if this doesn't work I was going to just run an Operation with the syntax for the mutation written out.

**Comment by ondrowan** [comment]
You forgot to call `txn.mutate(mutation).expect("...")` before commiting it. The current code commited an empty transaction.

A sidenote: You don't need to convert `&str` to `String` if you are just comparing strings.

**Comment by davedbase** [comment]
....wow. Sorry for posting this. You're absolutely right. I missed it. Apologies!
