### ISSUE TITLE
Interest in switching from grpcio to tonic

### ISSUE THREAD

**Issue by nevi-me** [Swoorup/dgraph-rs#23]
Hi, would you accept a PR switching to tonic (based on tokio) if the PR retained the existing functionality (perhaps with some changes where unavoidable)?

The motivation for this PR is that trying to use `dgraph` on the new Apple OS requires one to build LLVM from source, because of `bindgen` relying on it.
Switching to tonic should in theory not cause any significant performance regression (if there's even any regression) as the transport layer is still the same.

**Comment by Swoorup** [comment]
Sure we can accept a PR.

**Comment by ondrowan** [comment]
@nevi-me There's another crate that already uses Tonic though: https://github.com/selmeci/dgraph-tonic

**Comment by nevi-me** [comment]
Thanks, I hadn't seen it. I'm closing this
